### ISSUE TITLE
Does this toolkit support upserts?

### ISSUE THREAD

**Issue by snowch** [IBMStreams/streamsx.elasticsearch#13]
It isn't clear if this toolkit only supports inserts or upserts.  Can you please confirm?

**Comment by snowch** [comment]
I guess it doesn't support upserts:

```
// Add jsonDocuments to bulkRequest.
if (idToInsert != null) {
    bulkRequest.add(client.prepareIndex(indexToInsert, typeToInsert, idToInsert)
	.setSource(jsonDocuments));
} else {
    bulkRequest.add(client.prepareIndex(indexToInsert, typeToInsert)
    	.setSource(jsonDocuments));
}
```
Reference: [com.ibm.streamsx.elasticsearch.ElasticsearchIndex](https://github.com/IBMStreams/streamsx.elasticsearch/blob/master/com.ibm.streamsx.elasticsearch/impl/java/src/com/ibm/streamsx/elasticsearch/ElasticsearchIndex.java#L387-L394)

An upsert would require client.prepareUpdate() not client.prepareIndex() if I have understood correctly  see: https://www.elastic.co/guide/en/elasticsearch/client/java-api/5.4/java-docs-update.html

**Comment by brandtol** [comment]
With the next version of the toolkit the Java client (transport client) is dropped in favor of the JEST client (using the REST API). When using the idNameAttribute parameter, the application can provide the _id field directly instead of leting eslaticsearch create an _id. With this setup, a document with the same _id will be updated whenever it is indexed again. **So the upsert is working.**

It may lead to problems, when multiple applications update the same document concurrently. In that case the latest update will win. Elasticsearch offers 'Optimistic Concurrency Control' to detect and handle that situation. That feature is not supported by the toolkit so far. It would require to make the _version field accessible from the application.
